"""add cloudinary public id

Revision ID: 71c9acf20d73
Revises: a699ec3f67cb
Create Date: 2026-08-09 23:11:51.765326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c9acf20d73'
down_revision = 'a699ec3f67cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_images', schema=None) as batch_op:
        batch_op.drop_column('cloudinary_public_id')

    # ### end Alembic commands ###
