"""add requested_by_client to quotes

Revision ID: 721d94259136
Revises: 7b529c5f9c83
Create Date: 2026-08-03 22:56:50.553566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721d94259136'
down_revision = '7b529c5f9c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_by_client', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('requested_by_client')

    # ### end Alembic commands ###
