"""add portfolio images

Revision ID: 75c8cb6616ab
Revises: 9bc555dc1454
Create Date: 2026-08-02 16:46:35.889076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c8cb6616ab'
down_revision = '9bc555dc1454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_events_invoice_id', 'invoices', ['invoice_id'], ['id'], use_alter=True)

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_quotes_event_id', 'events', ['event_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quotes_event_id', type_='foreignkey')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_invoice_id', type_='foreignkey')

    # ### end Alembic commands ###
