"""add media_type to portfolio images

Revision ID: 7b529c5f9c83
Revises: defa770e6953
Create Date: 2026-08-03 10:36:47.102152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b529c5f9c83'
down_revision = 'defa770e6953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_images', schema=None) as batch_op:
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
