"""add account reference and requested by client columns

Revision ID: d7deee78074f
Revises: 721d94259136
Create Date: 2026-08-07 08:34:16.629205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7deee78074f'
down_revision = '721d94259136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_reference', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_payment_transactions_account_reference'), ['account_reference'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_account_reference'))
        batch_op.drop_column('account_reference')

    # ### end Alembic commands ###
